project:
  type: website

website:
  title: "Wright Labs Tutorials"
  favicon: images/favicon.ico
  sidebar:
    logo: images/bar_logo_alt.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      
      - href: chapter1-0.qmd
        section: Using the Cluster
        contents:
          - href: chapter1-1.qmd
            text: Connecting to the Cluster
          - href: chapter1-2.qmd
            text: Unix Shell Basics
          - href: chapter1-3.qmd
            text: Cluster Basics
      
      - href: chapter2-0.qmd
        section: 16s Tutorial
        contents:
          - href: chapter2-1.qmd
            text: Program & Data Aquisition
          - href: chapter2-2.qmd
            text: Qiime2 Basics
          - href: chapter2-3.qmd
            text: JC Qiime2 Pipeline                         
  page-footer:
    left: |
      Tutorials written by Wright Labs.
    right: |
      This site was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme:
      - cosmo
      - custom.scss
    code-link: true
    page-layout: article
    toc: true
    toc-location: right
    toc-title: ""
    page-navigation: true
    lightbox: true
    callout-appearance: simple

editor: source
